services:
    wb-tariffs-service:
        build: .
        container_name: wb-tariffs-service
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:17-alpine
        container_name: wb-tariffs-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -h ${DB_HOST}']
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    pgdata:
