services:
    wb-tariffs-service:
        build: .
        container_name: wb-tariffs-service
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres:17-alpine
        container_name: wb-tariffs-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
